swipe:
  3:
    left:
      command: "xdotool key Super+shift+a"
      # "xdotool keydown alt key Tab; sleep 1.5; xdotool keyup alt" # History forward
    right:
      command: "xdotool key Super+shift+d" # History back
    up:
      command: "xdotool key Super+a" # Activity
    down:
      command: "xdotool key super" # Activity
  4:
    left:
      command: "xdotool key Super+ctrl+Right" # Switch to next workspace
    right:
      command: "xdotool key Super+ctrl+Left" # Switch to previous workspace
    up:
      command: "xdotool key Shift+Print" # Switchctrl+alt+ to next workspace
    down:
      command: "xdotool key Print" # Switch to previous workspace
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
hold:
  4:
    command: "xdotool key super" # Activity
  3: 
    command: "xdotool key Print"
